name: checks

on:
  push:
    branches:
      - main
      - stage
      - dev
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - frontend-lint
          - frontend-format
          - backend-typecheck
          - backend-lint
          - backend-format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Run ${{ matrix.command }}
        run: uvx lefthook run pre-commit --command ${{ matrix.command }} --all-files
